export const ProductList = [
  {
    id: 1,
    name: 'BP PARABOLAN',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '100mg/ml',
    price: '39,5',
  },
  {
    id: 2,
    name: 'BP PRIMOBOL',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '100mg/ml',
    price: '39,5',
  },
  {
    id: 3,
    name: 'BP STROMBAJECT AQUA ',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '50mg/ml',
    price: '13,75',
  },
  {
    id: 4,
    name: 'BP SUSTANDROL',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '250mg/ml',
    price: '13,75',
  },
  {
    id: 5,
    name: 'BP ENANDROL',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '250mg/ml',
    price: '13,75',
  },
  {
    id: 6,
    name: 'BP PROPANDROL',
    description: 'description BP',
    volume: '10 ml',
    volumPack: '100mg/ml',
    price: '7,7',
  },
];
